# -*- coding: utf-8 -*-
# -*- encoding: utf-8 -*-

from django.conf.urls.defaults import *
from videoclient.settings import *
from videoclient.po2 import *

urlpatterns = patterns('',
    (r'^$', 'videoclient.po4.views.ident'),                   
    (r'^persons/', 'videoclient.po4.views.persons'),
    (r'^anketaclear/', 'videoclient.po4.views.anketaclear'),
    (r'^anketaperson/(?P<id>\d+)/(?P<id2>\d+)/', 'videoclient.po4.views.anketaperson'),
    (r'^anketaperson/(?P<id>\d+)/', 'videoclient.po4.views.anketaperson'),
    (r'^anketaperson/', 'videoclient.po4.views.anketaperson'),
    (r'^addphotoperson/(?P<select_page>.+)/(?P<id>.+)/', 'videoclient.po4.views.addphotoperson'),
    (r'^choose_camera/(?P<select_page>.+)/(?P<id>.+)/', 'videoclient.po4.views.choose_camera'),
    (r'^learn_camera/(?P<select_page>.+)/(?P<communicator>\d+)/(?P<numcamera>\d+)/(?P<person>.*)/', 'videoclient.po4.views.learn_camera'),
    (r'^photosperson/(?P<id>\d+)/', 'videoclient.po4.views.photosperson'),
    (r'^help/', 'videoclient.po4.views.help'),
    (r'^historychange/', 'videoclient.po4.views.historychange'),
    (r'^historychangep1/', 'videoclient.po4.views.historychangep1'),
    (r'^kppadd/', 'videoclient.po4.views.kppadd'),
    (r'^kppedit/', 'videoclient.po4.views.kppedit'),
    (r'^kpp/', 'videoclient.po4.views.kpp'),
    (r'^pageemployee/', 'videoclient.po4.views.pageemployee'),
    (r'^photosuser/', 'videoclient.po4.views.photosuser'),
    (r'^users/', 'videoclient.po4.views.users'),
    (r'^anketauser/(?P<id>\d+)/', 'videoclient.po4.views.anketauser'),
    (r'^anketauser/', 'videoclient.po4.views.anketauser'),
    (r'^anketaclearuser/', 'videoclient.po4.views.anketaclearuser'),
    (r'^visitors/', 'videoclient.po4.views.visitors'),
    (r'^visitorslist/', 'videoclient.po4.views.visitorslist'),
    (r'^anketavisitor/(?P<id>\d+)/(?P<id2>\d+)/', 'videoclient.po4.views.anketavisitor'),
    (r'^anketavisitor/(?P<id>\d+)/', 'videoclient.po4.views.anketavisitor'),
    (r'^anketavisitor/', 'videoclient.po4.views.anketavisitor'),
    (r'^photosvisitor/', 'videoclient.po4.views.photosvisitor'),
    (r'^staff/', 'videoclient.po4.views.staff'),
    (r'^stafflist/', 'videoclient.po4.views.stafflist'),
    (r'^anketastaff/(?P<id>\d+)/(?P<id2>\d+)/', 'videoclient.po4.views.anketastaff'),
    (r'^anketastaff/(?P<id>\d+)/', 'videoclient.po4.views.anketastaff'),
    (r'^anketastaff/', 'videoclient.po4.views.anketastaff'),
    (r'^photosstaff/', 'videoclient.po4.views.photosstaff'),
    (r'^ident/', 'videoclient.po4.views.ident'),
    (r'^visitorcard/*(?P<vcid>\d+)*', 'videoclient.po4.views.visitorcard'),
    (r'^repeatRecognition/', 'videoclient.po4.views.repeatRecognition'),
    (r'^movementProcess/*(?P<journalid>\d+)', 'videoclient.po4.views.movementProcess'),
    (r'^distortion_settings/(?P<communicator>\d+)/(?P<numcamera>\d+)/(?P<cameramode>\d+)/', 'videoclient.po4.views.distortion_settings'),
    (r'^settings_recognition/$', 'videoclient.po4.views.settings_recognition'),
    (r'^special/$', 'videoclient.po4.views.special'),
    (r'^events/$', 'videoclient.po4.views.events'),
    (r'^settings_interface/$', 'videoclient.po4.views.settings_interface'),
)
