SUCCESS = 0
ERROR_FORM = 1

UPLOAD_VK = 0
UPLOAD_COMP = 1

PREVIEW_ROOT="preview/"
STAR_PHOTO_PATH="store/photos.uni/"

WIZERS_ROOT = "wizers"
TINY_SIZE = (80,80)

PREVIEW_SIZEX = 160
PREVIEW_SIZEY = 120
FULL_SIZE_Max = 700
FULL_SIZE_Min = 370